name: Lint and Test

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - Pipfile
      - Dockerfile
      - '.github/worflows/*'

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install pipenv black
          pipenv install --system --skip-lock

      - name: Lint check with black
        run: pipenv run blackcheck

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':python: *Lint check*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}

  test:
    name: Python Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install pipenv pytest
          pipenv install --system --skip-lock

      - name: Test with pytest
        run: pipenv run test

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':pytest: *Test*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}

  audit:
    name: Python Audit
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --system --skip-lock

      - name: Vulnerability check
        run: pipenv check

      - name: Notify Result to Slack
        uses: homoluctus/slatify@master
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':pipenv: *Audit*'
          channel: '#ci_my_projects'
          url: ${{ secrets.SLACK_WEBHOOK }}
